apiVersion: 1

datasources:
  # Loki
  - name: Loki
    type: loki
    access: proxy
    orgId: 1
    url: http://loki:3100
    basicAuth: false
    isDefault: true
    version: 1
    editable: true

  # TimescaleDB
  - name: TimescaleDB
    type: postgres
    access: proxy
    orgId: 1
    url: postgres-timescale:5432
    user: postgres
    database: main_db
    basicAuth: false
    isDefault: false
    version: 1
    editable: true
    # FIX: Indent 'secureJsonData' children by 2 spaces
    secureJsonData:
      password: "password"
    # FIX: Indent 'jsonData' children by 2 spaces
    jsonData:
      sslmode: "disable"
      timescaledb: true